/** 日本語 UI（plainJapanese + japaneseCrmMessages）に合わせた e2e 用ラベル */
export const ja = {
  appTitle: "お客様管理",
  welcomeTitle: "お客様管理へようこそ",
  firstName: "名（下の名前）",
  lastName: "姓（苗字）",
  email: "メールアドレス",
  password: "パスワード",
  createAccount: "利用者を登録",
  signIn: "ログイン",
  whatsNext: "次にすること",
  stepDone: (step: number) => `${step}/3 完了`,
  installApp: "お客様管理の初期設定",
  addFirstContact: "最初の担当者を登録",
  addFirstNote: "最初のメモを書く",
  newContact: "新しい担当者",
  femalePronoun: "女性",
  title: "役職・肩書き",
  company: "所属する企業",
  search: "探す",
  createCompany: (name: string) => `「${name}」を新規登録`,
  emailAddresses: "メールアドレス",
  phoneNumbers: "電話番号",
  emailPlaceholder: "メール",
  phonePlaceholder: "電話番号",
  add: "追加",
  linkedIn: "LinkedInのページ",
  background: "メモ（経歴、出会ったきっかけなど）",
  hasNewsletter: "お知らせメールを受け取る",
  accountManager: "担当の営業",
  save: "保存",
  createdToast: "登録しました",
  addNote: "メモを書く",
  addNotePlaceholder: "メモを書く",
  addThisNote: "このメモを追加",
  noteAddedToast: "メモを追加しました",
  youAddedNote: "あなたがメモを追加",
  me: "自分",
  latestActivity: "最近の動き",
  dashboard: "ダッシュボード",
  stores: "店舗",
  newStore: "新しい店舗",
  storeName: "店舗名",
  createStore: "店舗を登録",
  memberStore: "在籍店舗",
  zipLabel: "郵便番号",
  zipFormatError: "郵便番号は 123-4567 または 7 桁の数字で入力してください",
  duplicateStoreError: "同じ名前の店舗が既にあります",
  contacts: "担当者",
  noexcuseAppTitle: "noexcuse CRM",
  noexcuseContacts: "会員",
  noexcuseCompanies: "企業",
  noexcuseDeals: "入会管理",
  filterConditions: "検索条件",
  confirm: "確認",
  bulkTag: "ラベルを付ける",
  selectAll: "すべて選択",
  createNewTag: "新しいラベルを作る",
  tagName: "ラベル名",
  tagAddedToast: "2人にラベルを付けました",
  addTask: "タスクを追加",
  create: "作成",
  task: "タスク",
  tasks: "タスク",
  taskCount: (n: number) => `タスク ${n}件`,
  description: "内容",
  dueDate: "期限",
  type: "種類",
  call: "電話",
  taskAddedToast: "タスクを追加しました",
  upcomingTasks: "これからのタスク",
  regardingContact: (name: string) => `（${name}さんについて）`,
} as const;
