-- plugin-courses: コースマスタと店舗別提供コース

create table public.courses (
    id bigint generated by default as identity not null,
    name text not null,
    description text,
    course_type text not null,
    service_kind text not null,
    duration_minutes integer not null,
    is_active boolean not null default true,
    display_order integer not null default 100,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint courses_pkey primary key (id),
    constraint courses_name_not_blank check (length(trim(name)) > 0),
    constraint courses_duration_minutes_positive check (duration_minutes > 0),
    constraint courses_course_type_check check (course_type in ('single', 'membership', 'ticket')),
    constraint courses_service_kind_check check (service_kind in ('training', 'stretch', 'training_and_stretch'))
);

create unique index courses_name_lower_unique on public.courses (lower(trim(name)));
create index courses_display_order_id_idx on public.courses (display_order, id);

create table public.course_stores (
    id bigint generated by default as identity not null,
    course_id bigint not null,
    store_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint course_stores_pkey primary key (id),
    constraint course_stores_course_id_store_id_key unique (course_id, store_id),
    constraint course_stores_course_id_fkey foreign key (course_id) references public.courses (id) on update cascade on delete cascade,
    constraint course_stores_store_id_fkey foreign key (store_id) references public.stores (id) on update cascade on delete cascade
);

create index course_stores_store_id_idx on public.course_stores (store_id);

create or replace function public.update_courses_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger update_courses_updated_at
    before update on public.courses
    for each row
    execute function public.update_courses_updated_at();

alter table public.courses enable row level security;
alter table public.course_stores enable row level security;

grant delete, insert, select, update on table public.courses to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.courses to service_role;
grant delete, insert, select, update on table public.course_stores to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.course_stores to service_role;

create policy "Enable read access for authenticated users" on public.courses for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.courses for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.courses for update to authenticated using (true) with check (true);
create policy "Course Delete Policy" on public.courses for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.course_stores for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.course_stores for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.course_stores for update to authenticated using (true) with check (true);
create policy "Course Store Delete Policy" on public.course_stores for delete to authenticated using (true);
