-- plugin-training-content（Phase 1）: 種目マスタ（カテゴリ＝部位 + 種目）

-- 種目カテゴリ（部位）
create table public.training_types (
    id bigint generated by default as identity not null,
    name text not null,
    display_order integer not null default 100,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint training_types_pkey primary key (id),
    constraint training_types_name_not_blank check (length(trim(name)) > 0)
);

create unique index training_types_name_lower_unique on public.training_types (lower(trim(name)));
create index training_types_display_order_id_idx on public.training_types (display_order, id);

-- 種目（カテゴリ配下）
create table public.training_groups (
    id bigint generated by default as identity not null,
    training_type_id bigint not null,
    name text not null,
    description text,
    display_order integer not null default 100,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint training_groups_pkey primary key (id),
    constraint training_groups_name_not_blank check (length(trim(name)) > 0),
    constraint training_groups_training_type_id_fkey
        foreign key (training_type_id) references public.training_types (id) on update cascade on delete restrict
);

-- 同一カテゴリ内では種目名を一意にする
create unique index training_groups_type_name_lower_unique
    on public.training_groups (training_type_id, lower(trim(name)));
create index training_groups_training_type_id_idx on public.training_groups (training_type_id);
create index training_groups_display_order_id_idx on public.training_groups (display_order, id);

-- updated_at 自動更新
create or replace function public.update_training_content_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger update_training_types_updated_at
    before update on public.training_types
    for each row
    execute function public.update_training_content_updated_at();

create trigger update_training_groups_updated_at
    before update on public.training_groups
    for each row
    execute function public.update_training_content_updated_at();

alter table public.training_types enable row level security;
alter table public.training_groups enable row level security;

-- マスタは全店舗共通。認証済みユーザーに CRUD を許可（courses 相当）
grant delete, insert, select, update on table public.training_types to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.training_types to service_role;
grant delete, insert, select, update on table public.training_groups to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.training_groups to service_role;

create policy "Enable read access for authenticated users" on public.training_types for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.training_types for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.training_types for update to authenticated using (true) with check (true);
create policy "Training Type Delete Policy" on public.training_types for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.training_groups for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.training_groups for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.training_groups for update to authenticated using (true) with check (true);
create policy "Training Group Delete Policy" on public.training_groups for delete to authenticated using (true);
