-- plugin-stores: 店舗マスタと会員の在籍店舗

create table public.stores (
    id bigint generated by default as identity not null,
    name text not null,
    area_code text,
    zip text,
    address text,
    build text,
    created_at timestamp with time zone not null default now(),
    constraint stores_pkey primary key (id)
);

alter table public.stores enable row level security;

alter table public.contacts
    add column store_id bigint;

alter table public.contacts
    add constraint contacts_store_id_fkey
    foreign key (store_id) references public.stores (id)
    on update cascade
    on delete set null;

grant delete on table public.stores to authenticated;
grant insert on table public.stores to authenticated;
grant select on table public.stores to authenticated;
grant update on table public.stores to authenticated;

grant delete on table public.stores to service_role;
grant insert on table public.stores to service_role;
grant references on table public.stores to service_role;
grant select on table public.stores to service_role;
grant trigger on table public.stores to service_role;
grant truncate on table public.stores to service_role;
grant update on table public.stores to service_role;

create policy "Enable read access for authenticated users"
    on public.stores
    for select
    to authenticated
    using (true);

create policy "Enable insert for authenticated users only"
    on public.stores
    for insert
    to authenticated
    with check (true);

create policy "Enable update for authenticated users only"
    on public.stores
    for update
    to authenticated
    using (true)
    with check (true);

create policy "Store Delete Policy"
    on public.stores
    for delete
    to authenticated
    using (true);
